package(default_visibility = ["//visibility:public"])

cc_test(
    name = "star_test",
    srcs = glob(["**/*.cc"]),
    #hdrs = glob(["**/*.h"]),
    deps = [
        "//star:star_lib",
        "@gtest//:gtest_main",
    ],
)
